# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate Javadoc HTML

on:
  push:
    branches: [ main ]

jobs:
  javadoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Cache Gradle packages 2
      uses: actions/cache@v2
      with:
        path: ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate KDoc
      run: ./gradlew dokkaHtmlMultiModule
    - name: Rename navigation.html
      run: mv build/dokka/htmlMultiModule/navigation.html build/dokka/htmlMultiModule/index.html
    - name: Delete existing docs folder
      run: rm -rf ./docs
    - name: Move KDoc to docs folder
      run: mv build/dokka/htmlMultiModule ./docs
    - name: Commit KDoc
      uses: EndBug/add-and-commit@v5
      with:
        message: "Updated KDoc"
        add: "./docs"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
